# Generated by Django 5.2 on 2025-09-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logistics', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giglshipment',
            name='order_shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_item', to='orders.ordershipment'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
