<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-15 17:10
=======
# Generated by Django 5.2 on 2025-09-18 11:55
>>>>>>> 6c44d1b (Migration files)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_variant', to='products.productvariant'),
        ),
    ]
