<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-07 07:39
=======
# Generated by Django 5.2 on 2025-09-07 12:49
>>>>>>> main-migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giglexperiencecentre',
            name='state',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='weight_measurement',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram')], max_length=10),
        ),
        migrations.AlterField(
            model_name='station',
            name='state_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
