# Generated by Django 5.2 on 2025-11-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GIGLExperienceCentre',
        ),
        migrations.RemoveField(
            model_name='giglshipment',
            name='order_shipment',
        ),
        migrations.DeleteModel(
            name='GIGLWebhookCredentials',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='GIGLShipment',
        ),
    ]
