<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-07 07:39
=======
# Generated by Django 5.2 on 2025-09-07 12:49
>>>>>>> main-migration

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='reminder_24h_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='reminder_2h_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='reminder_48h_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='carts_cart_updated_c06937_idx'),
        ),
    ]
