# Generated by Django 5.2 on 2025-09-18 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='categories__name_e3ad98_idx')],
            },
        ),
    ]
