# Generated by Django 5.2 on 2025-09-18 11:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerKYCAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits long.', regex='^\\d{11}$')])),
                ('street', models.CharField(max_length=500)),
                ('landmark', models.CharField(max_length=250)),
                ('lga', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerKYCCAC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rc_number', models.CharField(max_length=8, unique=True)),
                ('company_type', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('cac_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerKYCNIN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nin', models.CharField(max_length=11)),
                ('selfie', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('nin_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerSocials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerKYC',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kyc', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('info_completed_notified', models.BooleanField(default=False)),
                ('status_notified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='sellers.sellerkycaddress')),
                ('cac', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellers.sellerkyccac')),
                ('nin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sellers.sellerkycnin')),
                ('socials', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sellers.sellersocials')),
            ],
        ),
    ]
