# Generated by Django 5.2 on 2025-11-13 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerkyc',
            name='partial_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='partial_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='partial_verified_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerkycaddress',
            name='additional_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits long.', regex='^\\d{11}$')]),
        ),
    ]
