"""
Django settings for Horal_Backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
import os

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Reading from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'sellers',
    'notifications',
    'products',
    'carts',
    'orders',
    'anymail',
    'drf_yasg',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'carts.middleware.SessionFixMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom middleware
    'carts.middleware.CartMiddleware',
    
]


# Add Cors settings
# CORS_ALLOWED_ORIGINS = [
#     'https://www.horal.ng',
#     "http://localhost:3000",       # React dev server
#     "http://127.0.0.1:3000",
# ]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SWAGGER_DOCS_BASE_URL= env('SWAGGER_DOCS_BASE_URL')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
    'rest_framework.authentication.SessionAuthentication', 
    'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', # Don't Touch! Override in your view
    ],    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30,
}

SWAGGER_SETTINGS = {
   'USE_SESSION_AUTH': False
}

FORCE_SCRIPT_NAME = env('FORCE_SCRIPT_NAME')


from datetime import timedelta

#JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Use the same secret key as your Django settings
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Google OAuth2 settings
GOOGLE_OAUTH = {
    "WEB_CLIENT_ID": env('WEB_CLIENT_ID'),
    "MOBILE_CLIENT_ID": env('MOBILE_CLIENT_ID'),
    "CLIENT_SECRET": env('CLIENT_SECRET'),
    "REDIRECT_URI": env('REDIRECT_URI'),
}


# Mailgun settings
# MAILGUN_API_KEY = env('MAILGUN_API_KEY')
# MAILGUN_DOMAIN = env('MAILGUN_DOMAIN')
# MAILGUN_API_URL = env('MAILGUN_API_URL').format(MAILGUN_DOMAIN)

# EMAIL_BACKEND = env('EMAIL_BACKEND')
# ANYMAIL = {
#     'MAILGUN_API_KEY': MAILGUN_API_KEY,
#     'MAILGUN_SENDER_DOMAIN': MAILGUN_DOMAIN,
# }

# DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Redis configuration for django
# CACHES = {
#     "default": {
#         "BACKEND": env('BACKEND'),
#         "LOCATION": env('LOCATION'),
#         "OPTIONS": {
#             "CLIENT_CLASS": env('CLIENT_CLASS'),
#         }
#     }
# }


import urllib.parse as urlparse

redis_url = os.environ.get("REDIS_URL")
url = urlparse.urlparse(redis_url)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{url.hostname}:{url.port}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": url.password,
        }
    }
}



ROOT_URLCONF = 'Horal_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Horal_Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# auth user model
AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # Add additional backends if necessary
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


CSRF_TRUSTED_ORIGINS = [
    'https://horal-backend.up.railway.app',
]

STATIC_URL = 'static/'
# MEDIA_URL = 'media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # This is where collectstatic puts files

# Optional compression and caching:
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
