"""
Django settings for Horal_Backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
import os

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Reading from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'sellers',
    'products',
    'carts',
    'orders',
    'favorites',
    'categories',
    'subcategories',
    'shops',
    'ratings',
    'user_profile',
    'payment',
    'support',
    'notifications',
    'sellers_dashboard',
    'wallet',
    'media', 
    'logistics',
    'anymail',
    'drf_yasg',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',
    # Celery result backend
    'django_celery_results',
    'storages',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'carts.middleware.SessionFixMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom middleware
    'carts.middleware.CartMiddleware',
    # 'sellers_dashboard.middleware.reauth_middleware.DashboardReauthMiddleware',
    
]


if os.getenv('DJANGO_ENV') == 'development':  # or DEBUG
    MIDDLEWARE = [
        mw for mw in MIDDLEWARE
        if mw != 'django.middleware.csrf.CsrfViewMiddleware'
    ]


# Add Cors settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'https://www.horal.ng',
    "https://horal.ng",
    "http://localhost:3000",       # React dev server
    "http://127.0.0.1:3000",
]

# Set trailing slash automatically
APPEND_SlASH = True


if DEBUG or os.getenv("DJANGO_ENV") == "development":
    # Development: frontend is http://localhost:3000
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
else:
    # Production: frontend and backend served over HTTPS
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"



CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=["https://ecommerce-backend-a5oq.onrender.com", "http://localhost:3000"]
)


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SWAGGER_DOCS_BASE_URL= env('SWAGGER_DOCS_BASE_URL')

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "Horal_Backend.api.custom_exception_handler",
    'DEFAULT_AUTHENTICATION_CLASSES': [
    'rest_framework.authentication.SessionAuthentication', 
    'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', # Don't Touch! Override in your view
    ],    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30,
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer <token>"'
        }
    },
    'SECURITY_REQUIREMENTS': [
        {'Bearer': []}
    ],

    'USE_SESSION_AUTH': False,
    'PERSIST_AUTH': True,
    'REFETCH_SCHEMA_WITH_AUTH': True,
    'REFETCH_SCHEMA_ON_LOGOUT': True,
}

REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
}


# FORCE_SCRIPT_NAME = env('FORCE_SCRIPT_NAME')


from datetime import timedelta

#JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Use the same secret key as your Django settings
    'AUTH_HEADER_TYPES': ('Bearer',),
    "AUTH_COOKIE": "access",  # Cookie name
    "AUTH_COOKIE_SECURE": False, # Set to True in production
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_PATH": "/", 
    "AUTH_COOKIE_SAMESITE": "None",  # Required for cross-site
}

# Google OAuth2 settings
GOOGLE_OAUTH = {
    "WEB_CLIENT_ID": env('WEB_CLIENT_ID'),
    "MOBILE_CLIENT_ID": env('MOBILE_CLIENT_ID'),
    "CLIENT_SECRET": env('CLIENT_SECRET'),
    "REDIRECT_URI": env('REDIRECT_URI'),
}

# Google API Key
GOOGLE_API_KEY = env('GOOGLE_API_KEY')
MAP_API_KEY = env('MAP_API_KEY')

# Bulk SMS API Token Integration
BULK_SMS_API = env('BULK_SMS_API')
BULK_SMS_LEGACY_API = env('BULK_SMS_LEGACY_API')
BULK_SMS_BASE_URL = env('BULK_SMS_BASE_URL')
BULK_SMS_SENDER_ID = env('BULK_SMS_SENDER_ID')
BULK_SMS_API_TOKEN = env("BULK_SMS_API_TOKEN")


# Mailgun settings
MAILGUN_API_KEY = env('MAILGUN_API_KEY')
MAILGUN_DOMAIN = env('MAILGUN_DOMAIN')
MAILGUN_API_URL = env('MAILGUN_API_URL').format(MAILGUN_DOMAIN)

EMAIL_BACKEND = env('EMAIL_BACKEND')
ANYMAIL = {
    'MAILGUN_API_KEY': MAILGUN_API_KEY,
    'MAILGUN_SENDER_DOMAIN': MAILGUN_DOMAIN,
}

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Redis configuration for django
# CACHES = {
#     "default": {
#         "BACKEND": env('BACKEND'),
#         "LOCATION": env('LOCATION'),
#         "OPTIONS": {
#             "CLIENT_CLASS": env('CLIENT_CLASS'),
#         }
#     }
# }


# Maximum retries
MAX_RETRIES = 3

# Paystack Payment Setup

# settings.py
PAYSTACK_SECRET_KEY = env('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = env('PAYSTACK_PUBLIC_KEY')
PAYSTACK_INITIALIZE_URL = env('PAYSTACK_INITIALIZE_URL')
PAYSTACK_VERIFY_URL = env('PAYSTACK_VERIFY_URL')
MOBILE_REDIRECT_URL = env('MOBILE_REDIRECT_URL')
WEB_REDIRECT_URL = env('WEB_REDIRECT_URL')
PAYSTACK_BASE_URL=env('PAYSTACK_BASE_URL')
PAYSTACK_TEST_MODE=env('PAYSTACK_TEST_MODE')


# Dojah API setting
DOJAH_APP_ID = env('DOJAH_APP_ID')
DOJAH_SECRET = env('DOJAH_SECRET')
DOJAH_PUBLIC_KEY = env('DOJAH_PUBLIC_KEY')
DOJAH_BASE_URL = env('DOJAH_BASE_URL')

import urllib.parse as urlparse

redis_url = env("REDIS_URL")
url = urlparse.urlparse(redis_url)


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{url.hostname}:{url.port}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # No PASSWORD, no SSL
        }
    }
}

# Celery settings
CELERY_BROKER_URL = f"redis://{url.hostname}:{url.port}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# No SSL needed for Render internal Redis
CELERY_BROKER_USE_SSL = None  

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"


# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": f"{url.scheme}://{url.hostname}:{url.port}/0",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "PASSWORD": url.password,
#             "SSL": url.scheme == "rediss",
#         }
#     }
# }


# # Celery setting
# import ssl

# # Change to its redis DB on production with custom redis setup
# CELERY_BROKER_URL = env("REDIS_URL")

# CELERY_BROKER_USE_SSL = {
#     # Change to SSL.CERT_REQUIRED when using own trusted custom redis
#     'ssl_cert_reqs': None # or ssl.CERT_NONE 
# }

# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'UTC' 


# FEZ Delivery Setup
FEZ_BASE_URL = env('FEZ_BASE_URL')
FEZ_USERNAME = env('FEZ_USERNAME')
FEZ_PASSWORD = env('FEZ_PASSWORD')
HORAL_FEZ_WEBHOOK = env('HORAL_FEZ_WEBHOOK')


ROOT_URLCONF = 'Horal_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Horal_Backend.wsgi.application'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Postgres DB on render
DATABASES = {
    'default': env.db('DATABASE_URL'),
}

# auth user model
AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # Add additional backends if necessary
]

# Setting for API Call
API_BASE_URL = env("API_BASE_URL")
SUPPORT_EMAIL = env("SUPPORT_EMAIL")
SUPPORT_PASSWORD = env("SUPPORT_PASSWORD")
RETURNS_EMAIL = env("RETURNS_EMAIL")
RETURNS_PASSWORD = env("RETURNS_PASSWORD")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# --------------------------------------------------
# Static / Media
# --------------------------------------------------
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=["https://ecommerce-backend-a5oq.onrender.com"],
)

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"



# ---- DigitalOcean Spaces ----
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="ams3")
AWS_S3_ENDPOINT_URL = env(
    "AWS_S3_ENDPOINT_URL", default="https://ams3.digitaloceanspaces.com"
)
AWS_DEFAULT_ACL = "public-read"

AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com/"
# -------------------------------------------------------------------
# Default PK
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Reauth TTL
IDLE_TIMEOUT = 6 * 60 * 60 # 6 hours of inactivity → require reauth
REAUTH_TTL = IDLE_TIMEOUT # 6 hours valid reauth token
OTP_TTL = 10 * 60 # OTP valid for 10 minutes
MAX_OTP_SENDS_PER_HOUR = 5
MAX_OTP_VERIFY_ATTEMPTS = 5
OTP_PEPPER = env("OTP_PEPPER")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

import os
import logging.handlers

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

APPS_TO_LOG = [
    "users", "wallet", "user_profile", "support", "subcategories", "shops",
    "sellers_dashboard", "sellers", "ratings", "products", "notifications",
    "media", "logistics", "favorites", "categories", "carts",
    "orders", "payments"
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {},
    "loggers": {},
}

for app in APPS_TO_LOG:
    handler_name = f"{app}_file"
    LOGGING["handlers"][handler_name] = {
        "class": "logging.handlers.TimedRotatingFileHandler",
        "filename": os.path.join(LOG_DIR, f"{app}.log"),
        "when": "midnight",
        "interval": 1,
        "backupCount": 30,  # keeps 30 days
        "formatter": "verbose",
    }
    LOGGING["loggers"][app] = {
        "handlers": [handler_name],
        "level": "DEBUG",
        "propagate": False,
    }


# category lists
CATEGORIES = {
    "fashion": [
        "clothing (men and women)", "shoes (men and women)", "bags", "jewelries",
        "watches", "eyewear", "underwear & sleepwear", "jerseys", "hats & caps", "swimwear", "others"
    ],
    "health and beauty": [
        "skincare", "makeup", "hair care", "fragrances", "wellness & supplements", "oral hygiene", "others"
    ],
    "foods": [
        "fresh produce", "meat, poultry & seafood", "dairy & eggs", "beverages (non-alcoholic)",
        "baked goods", "frozen foods", "fruits", "vegetables", "grains or cereals", "legumes or pulses",
        "nuts and seeds", "meat and poultry", "fish and seafood", "dairy", "eggs", "fats and oils", "herbs and spices",
        "confectionery and snacks", "others"
    ],
    "vehicles": [
        "cars", "motorcycles", "buses & vans", "vehicle parts & accessories",
        "bicycles & scooters", "boats & watercraft", "trucks", "others"
    ],
    "gadget": [
        "smartphones", "tablets", "smartwatches & wearables", "drones",
        "cameras & photography gadgets", "portable audio", "gaming",
        "gps & navigation", "e-readers", "vr/ar devices", "others"
    ],
    "accessories": [
        "phone accessories", "laptop accessories", "camera accessories",
        "travel accessories", "wallets & cardholders", "umbrellas", "gloves", "belts", "others"
    ],
    "children": [
        "Baby clothing (0-24 months)", "diapers & wipes", "feeding & nursing", "gear & travel",
        "toys & gifts (0-3 years)", "children clothing", "maternity wear", "baby food", "safety & health", "others"
    ],
    "electronics": [
        "televisions & home theater", "audio & hi-fi systems", "computers & laptops",
        "printers & scanners", "networking devices", "home appliances",
        "gaming PCs & components", "generators", "others"
    ]
}
