# Generated by Django 5.2 on 2025-09-18 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('support', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='support_team', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('current_tickets', models.PositiveIntegerField(default=0)),
                ('completed_tickets', models.PositiveIntegerField(default=0)),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('is_lead', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_support', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.message'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('returns', 'Returns'), ('support', 'Support')], db_index=True, max_length=20)),
                ('object_id', models.UUIDField()),
                ('ticket_state', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned')], db_index=True, default='unassigned', max_length=20)),
                ('re_assigned', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed')], db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('re_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_team', to='support.supportteam')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('re_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_assigned_team', to='support.supportteam')),
            ],
            options={
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_9415d6_idx'), models.Index(fields=['re_assigned_to', 'status'], name='support_tic_re_assi_d9a0c2_idx')],
            },
        ),
    ]
