# Generated by Django 5.2 on 2025-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_state',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned')], db_index=True, default='unassigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(choices=[('returns', 'Returns'), ('support', 'Support')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='tickets',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_9415d6_idx'),
        ),
        migrations.AddIndex(
            model_name='tickets',
            index=models.Index(fields=['re_assigned_to', 'status'], name='support_tic_re_assi_d9a0c2_idx'),
        ),
    ]
