# Generated by Django 5.2 on 2025-09-04 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='product_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productindex'),
        ),
    ]
