# Generated by Django 5.2 on 2025-09-15 16:57

import django.core.validators
import orders.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('street_address', models.CharField(blank=True, max_length=500, null=True)),
                ('local_govt', models.CharField(blank=True, max_length=150, null=True)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='Lagos', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits long.', regex='^\\d{11}$')])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('discount_applied', models.BooleanField(db_index=True, default=False)),
                ('product_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('is_returned', models.BooleanField(db_index=True, default=False)),
                ('is_return_requested', models.BooleanField(db_index=True, default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('reference', models.CharField(default=orders.utils.generate_reference, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('shipment_initiated', 'Shipment Initiated'), ('shipment_created', 'Shipment Created (CRT)'), ('shipment_created_by_customer', 'Shipment Created by Customer (MCRT)'), ('available_for_pickup', 'Available for Pick-Up (AD)'), ('shipment_picked_up', 'Shipment Picked Up (MPIK)'), ('shipment_arrived_final_destination', 'Shipment Arrived Final Destination (MAFD)'), ('out_for_delivery', 'Out for Delivery / With Courier (OFDU)'), ('delivered_to_customer_address', 'Delivered to Customer Address (MAHD)'), ('delivered_to_pickup_point', 'Delivered to Pickup Point (OKC)'), ('delivered_to_terminal', 'Delivered to Terminal (OKT)'), ('delayed_delivery', 'Delayed Delivery (DLD)'), ('delayed_pickup', 'Delayed Pickup (DLP)'), ('delayed_pickup_by_customer', 'Delayed Pickup By Customer')], max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_2h_sent', models.BooleanField(db_index=True, default=False)),
                ('reminder_24h_sent', models.BooleanField(db_index=True, default=False)),
                ('reminder_48h_sent', models.BooleanField(db_index=True, default=False)),
                ('auto_completion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
