# Generated by Django 5.2 on 2025-09-07 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='auto_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='reminder_24h_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='reminder_2h_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='reminder_48h_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_applied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_return_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_returned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'variant'], name='orders_orde_order_i_c8de3b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['shipment', 'variant'], name='orders_orde_shipmen_364619_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturnrequest',
            index=models.Index(fields=['order_item', 'status'], name='orders_orde_order_i_813c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordershipment',
            index=models.Index(fields=['seller', 'order'], name='orders_orde_seller__800497_idx'),
        ),
    ]
