# Generated by Django 5.2 on 2025-07-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
