# Generated by Django 5.2 on 2025-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='auto_completion_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
