# Generated by Django 5.2 on 2025-07-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_otp_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='otp_confirmed',
        ),
    ]
