# Generated by Django 5.2 on 2025-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordershipment_auto_completion_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershipment',
            old_name='tracking_number',
            new_name='fez_order_id',
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='waybill_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='status',
            field=models.CharField(blank=True, choices=[('shipment_initiated', 'Shipment Initiated'), ('accepted_at_inventory_facility', 'Accepted At Inventory Facility'), ('accepted_at_last_mile_hub', 'Accepted At Last Mile Hub'), ('assigned_to_a_rider', 'Assigned To A Rider'), ('delivered', 'Delivered'), ('dispatched', 'Dispatched'), ('enroute_to_last_mile_hub', 'Enroute To Last Mile Hub'), ('enroute_to_first_mile_hub', 'Enroute To First Mile Hub'), ('failed_pickup', 'Failed Pick-Up'), ('in_return_to_customer', 'In Return To Customer'), ('in_return_to_first_mile_hub', 'In Return To First Mile Hub'), ('in_return_to_last_mile_hub', 'In Return To Last Mile Hub'), ('pending_pickup', 'Pending Pick-Up'), ('pending_recipient_pickup', 'Pending Recipient Pick-Up'), ('picked_up', 'Picked-Up'), ('rejected_at_inventory_facility', 'Rejected At Inventory Facility'), ('rejected_at_last_mile_hub', 'Rejected At Last Mile Hub'), ('returned', 'Returned'), ('returned_to_first_mile_hub', 'Returned To First Mile Hub'), ('returned_to_last_mile_hub', 'Returned To Last Mile Hub')], max_length=50, null=True),
        ),
    ]
