# Generated by Django 5.2 on 2025-11-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_tracking_number_ordershipment_fez_order_id_and_more'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
    ]
