<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-15 17:10
=======
# Generated by Django 5.2 on 2025-09-18 11:55
>>>>>>> 6c44d1b (Migration files)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('file', 'File')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=500, unique=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
