# Generated by Django 5.2 on 2025-06-22 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='accessoryproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='healthandbeautyproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_beauty_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='healthandbeautyproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_beauty_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='healthandbeautyproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_beauty_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='healthandbeautyproduct',
            name='images',
            field=models.ManyToManyField(related_name='health_beauty_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='images',
            field=models.ManyToManyField(related_name='gadget_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='images',
            field=models.ManyToManyField(related_name='food_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='images',
            field=models.ManyToManyField(related_name='fashion_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='images',
            field=models.ManyToManyField(related_name='electronics_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='images',
            field=models.ManyToManyField(related_name='baby_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='accessoryproduct',
            name='images',
            field=models.ManyToManyField(related_name='accessory_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='occasion',
            field=models.ManyToManyField(blank=True, related_name='fashion_products', to='products.occasion'),
        ),
        migrations.AddField(
            model_name='productindex',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vehicleproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='vehicleproduct',
            name='images',
            field=models.ManyToManyField(related_name='vehicle_products', to='products.imagelink'),
        ),
        migrations.AddField(
            model_name='vehicleproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='vehicleproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_products', to='subcategories.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='healthandbeautyproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_health_beauty_product_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='gadgetproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_gadget_product_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='foodproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_food_product_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='electronicsproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_electronics_product_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='childrenproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_children_product_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='accessoryproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_accessory_product_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='fashionproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_fashion_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['category_name'], name='products_pr_categor_b0c990_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['object_id'], name='products_pr_object__ae5003_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productindex',
            unique_together={('object_id', 'content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('content_type', 'object_id', 'standard_size', 'color', 'custom_size_unit', 'custom_size_value')},
        ),
        migrations.AddConstraint(
            model_name='vehicleproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_vehicle_product_per_shop'),
        ),
    ]
