<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-15 17:10
=======
# Generated by Django 5.2 on 2025-09-18 11:55
>>>>>>> 6c44d1b (Migration files)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='accessoryproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='accessoryimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.accessoryproduct'),
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='childrenimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.childrenproduct'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='electronicsimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.electronicsproduct'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='fashionimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.fashionproduct'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.foodproduct'),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='gadgetimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.gadgetproduct'),
        ),
        migrations.AddField(
            model_name='healthandbeautyproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_beauty_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='healthandbeautyproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_beauty_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='healthandbeautyproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_beauty_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='healthandbeautyimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.healthandbeautyproduct'),
        ),
        migrations.AddField(
            model_name='productindex',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='productindex',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='recentlyviewedproduct',
            name='product_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productindex'),
        ),
    ]
