# Generated by Django 5.2 on 2025-09-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_initial'),
        ('shops', '0001_initial'),
        ('subcategories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyviewedproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='vehicleproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='vehicleproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_products', to='subcategories.subcategory'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.vehicleproduct'),
        ),
        migrations.AddIndex(
            model_name='accessoryproduct',
            index=models.Index(fields=['slug'], name='products_ac_slug_a4cafa_idx'),
        ),
        migrations.AddIndex(
            model_name='accessoryproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_ac_title_c4a3d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessoryproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_accessory_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='childrenproduct',
            index=models.Index(fields=['slug'], name='products_ch_slug_ad77e6_idx'),
        ),
        migrations.AddIndex(
            model_name='childrenproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_ch_title_66a145_idx'),
        ),
        migrations.AddConstraint(
            model_name='childrenproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_children_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='electronicsproduct',
            index=models.Index(fields=['slug'], name='products_el_slug_d41807_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_el_title_62a653_idx'),
        ),
        migrations.AddConstraint(
            model_name='electronicsproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_electronics_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='fashionproduct',
            index=models.Index(fields=['slug'], name='products_fa_slug_f03b27_idx'),
        ),
        migrations.AddIndex(
            model_name='fashionproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_fa_title_5e7a77_idx'),
        ),
        migrations.AddConstraint(
            model_name='fashionproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_fashion_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['slug'], name='products_fo_slug_dc935b_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_fo_title_dd90c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_food_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='gadgetproduct',
            index=models.Index(fields=['slug'], name='products_ga_slug_c1b9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='gadgetproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_ga_title_e6c71b_idx'),
        ),
        migrations.AddConstraint(
            model_name='gadgetproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_gadget_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='healthandbeautyproduct',
            index=models.Index(fields=['slug'], name='products_he_slug_4abff1_idx'),
        ),
        migrations.AddIndex(
            model_name='healthandbeautyproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_he_title_a135f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthandbeautyproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_health_beauty_product_per_shop'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['category', 'sub_category'], name='products_pr_categor_886cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['object_id'], name='products_pr_object__ae5003_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['price'], name='products_pr_price_b6e50e_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['state'], name='products_pr_state_faa0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['local_govt'], name='products_pr_local_g_3568b4_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['brand'], name='products_pr_brand_7f436d_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['condition'], name='products_pr_conditi_d924db_idx'),
        ),
        migrations.AddIndex(
            model_name='productindex',
            index=models.Index(fields=['is_published'], name='products_pr_is_publ_463a6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productindex',
            unique_together={('object_id', 'content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('content_type', 'object_id', 'standard_size', 'color', 'custom_size_unit', 'custom_size_value')},
        ),
        migrations.AddConstraint(
            model_name='recentlyviewedproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product_index'), name='unique_user_product_view'),
        ),
        migrations.AddConstraint(
            model_name='recentlyviewedproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_key', 'product_index'), name='unique_session_product_view'),
        ),
        migrations.AddIndex(
            model_name='vehicleproduct',
            index=models.Index(fields=['slug'], name='products_ve_slug_5de8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleproduct',
            index=models.Index(fields=['title', 'is_published'], name='products_ve_title_ef0f34_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleproduct',
            constraint=models.UniqueConstraint(fields=('title', 'brand', 'category', 'shop'), name='unique_vehicle_product_per_shop'),
        ),
    ]
