# Generated by Django 5.2 on 2025-09-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
