# Generated by Django 5.2 on 2025-09-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
