# Generated by Django 5.2 on 2025-10-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productindex_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='condition',
            field=models.CharField(blank=True, choices=[('fresh', 'Fresh'), ('frozen', 'Frozen'), ('canned', 'Canned'), ('chilled_refrigerated', 'Chilled or Refrigerated'), ('dried_dehydrated', 'Dried or Dehydrated'), ('freeze_dried', 'Freeze-Dried'), ('smoked', 'Smoked'), ('ready_to_eat', 'Ready-To-Eat'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
