# Generated by Django 5.2 on 2025-09-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_initial'),
        ('sellers_dashboard', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='dailyshopsales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_time_series', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_sales_category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_sales', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='monthlyshopsales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_time_series', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productratingsummary',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to='products.productindex'),
        ),
    ]
