# Generated by Django 5.2 on 2025-09-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0003_initial'),
        ('sellers_dashboard', '0002_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productratingsummary',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productratingsummary',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rating_summaries', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='rawsale',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AddField(
            model_name='rawsale',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='rawsale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productindex'),
        ),
        migrations.AddField(
            model_name='rawsale',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='rawsale',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='salesadjustment',
            name='raw_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sales', to='sellers_dashboard.rawsale'),
        ),
        migrations.AddField(
            model_name='topsellingproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_selling', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='weeklysales',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_sales_category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='weeklysales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_sales', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='weeklyshopsales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_time_series', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='yearlysales',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_sales_category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='yearlysales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_sales', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='yearlyshopsales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_time_series', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='dailysales',
            index=models.Index(fields=['shop', 'category', 'period_start'], name='sellers_das_shop_id_53d50c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysales',
            unique_together={('shop', 'category', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='dailyshopsales',
            index=models.Index(fields=['shop', 'period_start'], name='sellers_das_shop_id_062771_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyshopsales',
            unique_together={('shop', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='monthlysales',
            index=models.Index(fields=['shop', 'category', 'period_start'], name='sellers_das_shop_id_0982ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysales',
            unique_together={('shop', 'category', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='monthlyshopsales',
            index=models.Index(fields=['shop', 'period_start'], name='sellers_das_shop_id_b76b96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyshopsales',
            unique_together={('shop', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='productratingsummary',
            index=models.Index(fields=['shop'], name='sellers_das_shop_id_57b9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='topsellingproduct',
            index=models.Index(fields=['shop', 'month'], name='sellers_das_shop_id_d675bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topsellingproduct',
            unique_together={('shop', 'product', 'month')},
        ),
        migrations.AddIndex(
            model_name='weeklysales',
            index=models.Index(fields=['shop', 'category', 'period_start'], name='sellers_das_shop_id_67e5e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysales',
            unique_together={('shop', 'category', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='weeklyshopsales',
            index=models.Index(fields=['shop', 'period_start'], name='sellers_das_shop_id_eb4d09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyshopsales',
            unique_together={('shop', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='yearlysales',
            index=models.Index(fields=['shop', 'category', 'period_start'], name='sellers_das_shop_id_ce9a60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlysales',
            unique_together={('shop', 'category', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='yearlyshopsales',
            index=models.Index(fields=['shop', 'period_start'], name='sellers_das_shop_id_1cfc6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlyshopsales',
            unique_together={('shop', 'period_start')},
        ),
    ]
