# Generated by Django 5.2 on 2025-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='authorization_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
