# Generated by Django 5.2 on 2025-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='authorization_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
