# Generated by Django 5.2 on 2025-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paystacktransaction_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacktransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
