# Generated by Django 5.2 on 2025-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paystacktransaction_authorization_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
