# Generated by Django 5.2 on 2025-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paystacktransaction_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacktransaction',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
